package io.xarate.idea;

import com.intellij.openapi.module.Module;
import com.intellij.openapi.roots.ContentEntry;
import com.intellij.openapi.roots.ModifiableRootModel;
import com.intellij.testFramework.LightProjectDescriptor;
import com.intellij.testFramework.PsiTestUtil;
import org.jetbrains.annotations.NotNull;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class TestUtils {

    public static LightProjectDescriptor createDescriptorWithKarate() {
        return new LightProjectDescriptor() {
            @Override
            protected void configureModule(@NotNull Module module, @NotNull ModifiableRootModel model, @NotNull ContentEntry contentEntry) {
                List<String> karatePaths = java.util.Collections.singletonList(getKarateLibPath());
                PsiTestUtil.addProjectLibrary(model, "karate-core", karatePaths);
//                MavenDependencyUtil.addFromMaven(model, "io.karatelabs:karate-core:1.5.0.RC3");
            }
        };
    }

    /**
     Manually parses the ipr file which is expected to have been generated by the 'idea' gradle task.
     Other alternatives include:
     - IntelliJProjectConfiguration (see https://github.com/JetBrains/intellij-plugins/blob/master/cucumber-java/test/org/jetbrains/plugins/cucumber/java/CucumberJavaTestUtil.java for an example), but i could not get it to work
     - or MavenDependencyUtil.addFromMaven
     but those all try and fail to load the jps project 
     */
    private static String getKarateLibPath() {
        Path ipr = Path.of("xarate-idea.iml");
        try {
            // Requires the ipr file to be generated by the 'idea' gradle task.
            String karateLibLine = Files.readAllLines(ipr).stream().filter(line -> line.endsWith("jar!/\"/>") && line.contains("karate-core")).map(String::trim).findAny().orElseThrow(
                    () -> new IllegalStateException("Unable to find karate lib from " + ipr)
            );
            return karateLibLine.substring("<root url=\"jar://".length(), karateLibLine.length() - "/\"/>".length() - 1);
        } catch (java.io.IOException exc) {
            throw new IllegalStateException("Unable to find " + ipr + ", please make sure the 'idea' gradle task was run");
        }
    }


}
